### ISSUE TITLE
is_active does not seem to work in menus 

### ISSUE THREAD

**Issue by tommybickerdike** [venndr/theme-components#10]
Ref: https://venndr.github.io/liquid-docs/docs/objects/menu-item

Usage: https://github.com/venndr/theme-components/blob/master/venndr/components/snippets/navigation_horizontal.liquid#L5

I believe this is an issue in the API and not the theme

**Comment by tommybickerdike** [comment]
@nikcorg do you mind having a look at this or passing this onto the correct authorities.

**Comment by nikcorg** [comment]
@tommybickerdike yep, i'll have a look.

**Comment by tommybickerdike** [comment]
@nikcorg Hero!
