### ISSUE TITLE
Things I noticed when browsing the UB40 store

### ISSUE THREAD

**Issue by tomdmaguire** [venndr/theme-components#32]
I'm guessing most of these are known issues, awaiting deployment and/or awaiting some dev work, but here's a my list:

- if you load the homepage, click through to a product page, and then click the UB40 logo at the top to go back to the homepage, the back to website link is not visible. i don't think this really matters too much though...
- the LOAD MORE button is really a Next page button. if infinite scrolling is not going to be implemented, we should should switch to buttons that accurately reflect pagination
- [this product with variants](https://ub40.probitymerch.musicglue.store/products/circle-photo-baseball-tee) is showing "Select size" as button helper text. instead it should be showing "sold out" like [this product without variants](https://ub40.probitymerch.musicglue.store/products/acoustic-sessions-big-ep-1-cd)
- the lightbox background opacity sometimes doesn't show if you navigate to a product page via turbo links. to recreate, go to [this page](https://ub40.probitymerch.musicglue.store/shop?per=12&page=3) and click the "Food For Thought - Ringer Tee". then try and use the secondary image lightbox. think this might be something to do with pagination
- clothing page showing No Products Available
- left-hand-side menu (on desktop) doesn't need to be so wide
- there seems to be a lack of layout section definition 
  - should there be some sort of bottom border or drop shadow on the sticky header bar? 
  - should there be some separation of the footer from the rest of the content? either a top border on the footer or change the colour of the footer background?
  - maybe the above two things could be fixed by a few theme variable tweeks. if this is the case, maybe we could change the defaults for Probity stores?
  - should we do the global-theme grey background on right-hand-side of product pages thing?

**Comment by tommybickerdike** [comment]
Hey, I have split this into issues and added some comments below:

> if you load the homepage, click through to a product page, and then click the UB40 logo at the top to go back to the homepage, the back to website link is not visible. I don't think this really matters too much though...
This is a general JS race condition bug that is being worked on. Currently, the problems cannot be reproduced locally so solutions are being tried blind

> the LOAD MORE button is really a Next page button. if infinite scrolling is not going to be implemented, we should switch to buttons that accurately reflect pagination
This has been partially fixed. This issue also needs to be resolved: https://github.com/venndr/yggdrasil/issues/1109

- https://github.com/venndr/theme-components/issues/35

> clothing page showing No Products Available 
I believe this is a data issue.

- https://github.com/venndr/theme-probity/issues/4

- https://github.com/venndr/theme-probity/issues/5
