### ISSUE TITLE
Pre-order date still showing after release date has passed

### ISSUE THREAD

**Issue by tomdmaguire** [venndr/theme-components#34]
today is july 2nd

<img width="477" alt="image" src="https://user-images.githubusercontent.com/86268/124318476-908b6d80-db2d-11eb-8a46-9e254d4bfaea.png">

**Comment by tommybickerdike** [comment]
I have added extra logic to stop showing these. however, there is an oddity with the date being set to 11 pm on the day before you have set. `2021-07-04 23:00:00Z`. I'm not sure whether this is correct behaviour
