### ISSUE TITLE
Basket count - use ESI as data-attribute

### ISSUE THREAD

**Issue by tomdmaguire** [venndr/theme-components#41]
then use JS to animate where necessary

**Comment by tommybickerdike** [comment]
@tomdmaguire using ESI as a data attribute results in the following broken HTML:
```
<span class="basket-block__count-number" id="BasketCounter" data-turbolinks-permanent="" data-basket-count="<esi:include src=" _____esi_____="" basket="" total_items"="">"&gt;
				4
			</span>
			```

**Comment by tommybickerdike** [comment]
It works if I add it into Yggy like this: 
https://github.com/venndr/yggdrasil/pull/1122

**Comment by tomdmaguire** [comment]
we don't really want to be adding HTML into `basket_total_items.html.eex` because then we are introducing inflexibility and headaches for future theme authors

i imagine the fact that the esi code is not getting replaced properly is something to do with the parser that is looking for the ESI's - probably in Varnish.

lemme speak with Nikke

**Comment by nikcorg** [comment]
@tommybickerdike that's not valid markup. you'll have to add it as a child-node like in your [second example](https://github.com/venndr/theme-components/issues/41#issuecomment-877223466).

**Comment by tomdmaguire** [comment]
alright, i'm happy with second example if you are

**Comment by tommybickerdike** [comment]
Ok, thanks could you approve that PR? 
I have tried to make it as generic as possible to avoid theme author issues.

**Comment by nikcorg** [comment]
I would add the markup in the theme and leave the base template unchanged.

**Comment by tommybickerdike** [comment]
@nikcorg the issue this comes from is that the theme does not know when the bask

**Comment by tomdmaguire** [comment]
what you explain what you mean by add markup in the theme? the issue we are trying to solve is that we cant add the markup as desired in the theme due to the ESI not being allowed in a data attr

**Comment by nikcorg** [comment]
Why do you need the markup to be in a data-attr?

**Comment by tommybickerdike** [comment]
It allows CSS targeting with `[data-basket-count="0"]{ }` for CSS alterations on the empty state. 

Alternatively, a class of `basket-empty` could be used. However, this is more opinionated as it must assume a class naming structure that may not relate to the theme it is being applied to and only a

The third option is that I use JS in the theme to watch if the value changes and apply classes for CSS animation accordingly. I am starting to believe that this third option is the way forward here.

**Comment by nikcorg** [comment]
As long as the JS option doesn't make information from inaccessible to non-JS users (albeit, you can't complete a checkout without JS, so it's debatable whether it's an issue), go for it.

I'll let this simmer in my head a bit and see if I can find a fourth option, but in the mean time, do proceed with one of the three you've lined out.

**Comment by tommybickerdike** [comment]
Aye, aye, captain

**Comment by tomdmaguire** [comment]
> The third option is that I use JS in the theme to watch if the value changes and apply classes for CSS animation accordingly. I am starting to believe that this third option is the way forward here.

i think so too. it's a hack but gets us over the line for now

**Comment by tomdmaguire** [comment]
@tommybickerdike this can be closed now? i saw the new throbber on a store 👍
