### ISSUE TITLE
Product image improvements

### ISSUE THREAD

**Issue by tommybickerdike** [venndr/theme-components#52]
The current product detail Image zooming plugin:
- does not on mobile (touch an image, then try to pinch zoom. It moves all around)
- not great on desktop (opens centrally, but not larger than the original in the case of the primary image)

Solution proposal examples: 
https://www.made.com/elka-peacock-armchair-cane
https://www.counter-print.co.uk/products/web-design-the-evolution-of-the-digital-world-1990-today

- on desktop, all images will be large so there is no need to open larger
- on mobile, it will utilise the already installed slideshow plugin
- the browsers in-built zooming functionality can be utilised for any extra zooming the user wants

**Comment by jgwmaxwell** [comment]
> • on desktop, all images will be large so there is no need to open larger

I'd like to discuss this - being able to zoom in without opening in a new tab and then zooming into it is super useful.

**Comment by tommybickerdike** [comment]
@jgwmaxwell I don't want it to open in a new tab, the suggestion is that the images are just larger by default as on the examples. So the large size and high resolution are already present on the page.

Alternatively, we could keep the image size as is and re-implement the Amazon-style zoom on desktop, as we have on current stores:
https://www.entershikari.com/products/barcode-t-shirt

Primarily, there is no user benefit to what we currently have on desktop at the moment and it is potentially detrimental to UX on mobile:
https://ub40.probitymerch.musicglue.store/products/circle-photo-baseball-tee

**Comment by tommybickerdike** [comment]
A possible contender for desktop Zooming:
https://cdnjs.com/libraries/elevatezoom

This might be helpful: 
https://codepen.io/benfurfie/pen/RGEppp
